import { useEffect, useState } from "react";
import {
    ShieldAlert,
    ScanSearch,
    ChevronRight,
    X,
    MapPin,
    Shield,
    Clock3,
    Activity,
    Target,
    Server
} from "lucide-react";
import { fetchAlerts } from "../services/alertService";

export default function Alerts() {
    const [alerts, setAlerts] = useState([]);
    const [selectedAlert, setSelectedAlert] = useState(null);
    const [drawerOpen, setDrawerOpen] = useState(false);

    useEffect(() => {
        loadAlerts();
    }, []);

    const loadAlerts = async () => {
        try {
            const data = await fetchAlerts();
            setAlerts(data);
        } catch (err) {
            console.log(err);
        }
    };

    const handleInvestigation = (alert) => {
        setSelectedAlert(alert);
        setDrawerOpen(true);
    };

    const closeDrawer = () => {
        setDrawerOpen(false);

        setTimeout(() => {
            setSelectedAlert(null);
        }, 300);
    };

    return (
        <>
            <div className="space-y-6">
                <h1 className="text-5xl font-black">
                    Threat Alerts
                </h1>

                <p className="text-zinc-400">
                    Detected security incidents generated by ThreatEye Detection Engine.
                </p>

                <div className="grid gap-6">
                    {alerts.length === 0 && (
                        <div className="rounded-xl border border-zinc-800 bg-[#11161d] p-8 text-center text-zinc-400">
                            No threats detected.
                        </div>
                    )}

                    {alerts.map((alert, index) => (
                        <div
                            key={index}
                            className="rounded-xl border border-red-500/30 bg-red-500/10 p-6"
                        >
                            <div className="flex items-start justify-between">
                                <div className="flex gap-5">
                                    <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-red-500/15 text-red-400">
                                        {alert.icon === "shield" ? (
                                            <ShieldAlert size={30} />
                                        ) : (
                                            <ScanSearch size={30} />
                                        )}
                                    </div>

                                    <div>
                                        <h2 className="text-2xl font-bold text-red-400">
                                            {alert.title}
                                        </h2>

                                        <div className="mt-3 space-y-1 text-zinc-300">
                                            <p>
                                                Source IP : {alert.source_ip}
                                            </p>

                                            <p>
                                                Attempts : {alert.count}
                                            </p>

                                            <p>
                                                Severity : {alert.severity}
                                            </p>

                                            <p>
                                                MITRE : {alert.mitre || "N/A"}
                                            </p>

                                            <p>
                                                Confidence : {alert.confidence ?? "--"}%
                                            </p>

                                            <p>
                                                Detected : {alert.detected_at || "--"}
                                            </p>
                                        </div>
                                    </div>
                                </div>

                                <div className="flex flex-col items-end gap-4">
                                    <div
    className={`rounded-full px-4 py-2 text-sm font-bold text-white ${
        alert.severity === "Critical"
            ? "bg-red-600"
            : alert.severity === "High"
                ? "bg-orange-500"
                : alert.severity === "Medium"
                    ? "bg-yellow-500 text-black"
                    : "bg-emerald-600"
    }`}
>
    {alert.severity.toUpperCase()}
</div>

                                    <button
                                        onClick={() => handleInvestigation(alert)}
                                        className="flex items-center gap-2 rounded-lg border border-zinc-700 px-4 py-2 text-sm transition hover:border-emerald-500 hover:text-emerald-400"
                                    >
                                        View Investigation

                                        <ChevronRight size={16} />
                                    </button>
                                </div>
                            </div>

                            <p className="mt-5 text-zinc-400">
                                {alert.recommendation}
                            </p>
                        </div>
                    ))}
                </div>
            </div>

            {selectedAlert && (
                <>
                    <div
                        onClick={closeDrawer}
                        className={`fixed inset-0 z-40 bg-black/60 backdrop-blur-sm transition-all duration-300 ${
                            drawerOpen
                                ? "opacity-100"
                                : "pointer-events-none opacity-0"
                        }`}
                    />

                    <div
                        className={`fixed right-0 top-0 z-50 flex h-screen w-[480px] flex-col border-l border-emerald-500/20 bg-[#0c1016] shadow-[0_0_50px_rgba(16,185,129,0.18)] transition-transform duration-300 ${
                            drawerOpen
                                ? "translate-x-0"
                                : "translate-x-full"
                        }`}
                    >
                        <div className="flex items-center justify-between border-b border-zinc-800 p-6">
                            <div>
                                <p className="text-sm uppercase tracking-[0.3em] text-emerald-400">
                                    Threat Investigation
                                </p>

                                <h2 className="mt-2 text-3xl font-bold">
                                    {selectedAlert.title}
                                </h2>
                            </div>

                            <button
                                onClick={closeDrawer}
                                className="rounded-lg border border-zinc-700 p-2 transition hover:border-red-500 hover:text-red-400"
                            >
                                <X size={20} />
                            </button>
                        </div>

                        <div className="flex-1 space-y-6 overflow-y-auto p-6">                            <div className="rounded-xl border border-zinc-800 bg-[#121821] p-5">
                                <div className="mb-4 flex items-center gap-2">
                                    <Activity size={18} className="text-emerald-400" />

                                    <h3 className="font-semibold">
                                        Incident Summary
                                    </h3>
                                </div>

                                <div className="space-y-3 text-sm">
                                    <div className="flex items-center justify-between">
                                        <span className="text-zinc-400">
                                            Incident ID
                                        </span>

                                        <span className="font-medium">
                                            {selectedAlert.id}
                                        </span>
                                    </div>

                                    <div className="flex items-center justify-between">
                                        <span className="text-zinc-400">
                                            Severity
                                        </span>

                                        <span
                                        className={`rounded-full px-3 py-1 text-xs font-bold ${
                                            selectedAlert.severity === "Critical"
                                                ? "bg-red-600 text-white"
                                                : selectedAlert.severity === "High"
                                                    ? "bg-orange-500 text-white"
                                                    : selectedAlert.severity === "Medium"
                                                        ? "bg-yellow-500 text-black"
                                                        : "bg-emerald-600 text-white"
                                        }`}
                                    >
                                        {selectedAlert.severity}
                                    </span>
                                    </div>

                                    <div className="flex items-center justify-between">
                                        <span className="flex items-center gap-2 text-zinc-400">
                                            <MapPin size={15} />
                                            Source IP
                                        </span>

                                        <span>
                                            {selectedAlert.source_ip}
                                        </span>
                                    </div>

                                    <div className="flex items-center justify-between">
                                        <span className="flex items-center gap-2 text-zinc-400">
                                            <Server size={15} />
                                            Destination
                                        </span>

                                        <span>
                                            {selectedAlert.destination}
                                        </span>
                                    </div>

                                    <div className="flex items-center justify-between">
                                        <span className="flex items-center gap-2 text-zinc-400">
                                            <Shield size={15} />
                                            MITRE ATT&CK
                                        </span>

                                        <span>
                                            {selectedAlert.mitre}
                                        </span>
                                    </div>

                                    <div className="flex items-center justify-between">
                                        <span className="text-zinc-400">
                                            Confidence
                                        </span>

                                        <span className="font-semibold text-emerald-400">
                                            {selectedAlert.confidence}%
                                        </span>
                                    </div>

                                    <div className="flex items-center justify-between">
                                        <span className="flex items-center gap-2 text-zinc-400">
                                            <Clock3 size={15} />
                                            Detected
                                        </span>

                                        <span>
                                            {selectedAlert.detected_at}
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div className="rounded-xl border border-zinc-800 bg-[#121821] p-5">
    <div className="mb-5 flex items-center gap-2">
        <Target
            size={18}
            className="text-cyan-400"
        />

        <h3 className="font-semibold">
            Threat Intelligence
        </h3>
    </div>

    <div className="space-y-5">
        <div className="grid grid-cols-3 gap-4">
            <div className="rounded-xl bg-[#0d131b] p-4 text-center">
                <p className="text-xs uppercase tracking-wider text-zinc-500">
                    Threat
                </p>

                <p className="mt-2 text-2xl font-bold text-red-400">
                    {selectedAlert.threat_score}
                </p>
            </div>

            <div className="rounded-xl bg-[#0d131b] p-4 text-center">
                <p className="text-xs uppercase tracking-wider text-zinc-500">
                    Risk
                </p>

                <p className="mt-2 text-2xl font-bold text-orange-400">
                    {selectedAlert.risk_score}
                </p>
            </div>

            <div className="rounded-xl bg-[#0d131b] p-4 text-center">
                <p className="text-xs uppercase tracking-wider text-zinc-500">
                    Confidence
                </p>

                <p className="mt-2 text-2xl font-bold text-emerald-400">
                    {selectedAlert.confidence}%
                </p>
            </div>
        </div>

        <div>
            <h4 className="mb-3 font-semibold text-cyan-400">
                Indicators of Compromise
            </h4>

            <div className="space-y-4">
                {Object.entries(selectedAlert.iocs).map(
                    ([key, values]) => (
                        <div key={key}>
                            <p className="mb-2 text-xs uppercase tracking-wider text-zinc-500">
                                {key}
                            </p>

                            <div className="flex flex-wrap gap-2">
                                {values.length === 0 ? (
                                    <span className="text-sm text-zinc-500">
                                        —
                                    </span>
                                ) : (
                                    values.map((value) => (
                                        <span
                                            key={value}
                                            className="rounded-lg border border-cyan-500/20 bg-cyan-500/10 px-3 py-1 text-xs text-cyan-300 transition hover:border-cyan-400 hover:bg-cyan-500/20"
                                        >
                                            {value}
                                        </span>
                                    ))
                                )}
                            </div>
                        </div>
                    )
                )}
            </div>
        </div>
    </div>
</div>

                            <div className="rounded-xl border border-zinc-800 bg-[#121821] p-5">
                                <h3 className="mb-3 font-semibold">
                                    Recommendation
                                </h3>

                                <p className="leading-7 text-zinc-400">
                                    {selectedAlert.recommendation}
                                </p>
                            </div>
                        </div>

                        <div className="flex gap-4 border-t border-zinc-800 p-6">
                            <button
                                className="flex-1 rounded-xl bg-red-600 py-3 font-semibold transition hover:bg-red-500"
                            >
                                Block IP
                            </button>

                            <button
                                className="flex-1 rounded-xl border border-emerald-500 py-3 font-semibold text-emerald-400 transition hover:bg-emerald-500 hover:text-black"
                            >
                                Create Incident
                            </button>
                        </div>
                    </div>
                </>
            )}
        </>
    );
}
