import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
    ShieldAlert,
    ScanSearch,
    ChevronRight,
    X,
    MapPin,
    Shield,
    Clock3,
    Activity,
    Target,
    Server,
    Ban,
    FileWarning,
    CircleAlert
} from "lucide-react";

import { fetchAlerts } from "../services/alertService";

const severityStyles = {
    Critical: {
        border: "border-red-500/30",
        background: "bg-red-500/10",
        title: "text-red-400",
        icon: "bg-red-500/15 text-red-400",
        badge: "bg-red-600 text-white"
    },

    High: {
        border: "border-orange-500/30",
        background: "bg-orange-500/10",
        title: "text-orange-400",
        icon: "bg-orange-500/15 text-orange-400",
        badge: "bg-orange-500 text-white"
    },

    Medium: {
        border: "border-yellow-500/30",
        background: "bg-yellow-500/10",
        title: "text-yellow-400",
        icon: "bg-yellow-500/15 text-yellow-400",
        badge: "bg-yellow-500 text-black"
    },

    Low: {
        border: "border-emerald-500/30",
        background: "bg-emerald-500/10",
        title: "text-emerald-400",
        icon: "bg-emerald-500/15 text-emerald-400",
        badge: "bg-emerald-600 text-white"
    }
};

export default function Alerts() {

    const [alerts, setAlerts] = useState([]);

    const [selectedAlert, setSelectedAlert] = useState(null);

    const [drawerOpen, setDrawerOpen] = useState(false);

    useEffect(() => {

        loadAlerts();

    }, []);

    async function loadAlerts() {

        try {

            const data = await fetchAlerts();

            setAlerts(data);

        }

        catch (error) {

            console.error(error);

        }

    }

    function handleInvestigation(alert) {

        setSelectedAlert(alert);

        setDrawerOpen(true);

    }

    function closeDrawer() {

        setDrawerOpen(false);

        setTimeout(() => {

            setSelectedAlert(null);

        }, 250);

    }

    return (

        <>

            <div className="space-y-6">

                <div>

                    <h1 className="text-5xl font-black">

                        Threat Alerts

                    </h1>

                    <p className="mt-2 text-zinc-400">

                        Detected security incidents generated by the ThreatEye Detection Engine.

                    </p>

                </div>

                <div className="grid gap-6">

                    {

                        alerts.length === 0 && (

                            <div className="rounded-xl border border-zinc-800 bg-[#11161d] p-10 text-center text-zinc-500">

                                No alerts found.

                            </div>

                        )

                    }

                    {

                        alerts.map((alert, index) => {

                            const styles =
                                severityStyles[alert.severity] ??
                                severityStyles.Low;

                            return (

                                <motion.div

                                    key={index}

                                    whileHover={{
                                        y: -4
                                    }}

                                    transition={{
                                        duration: 0.18
                                    }}

                                    className={`rounded-2xl border ${styles.border} ${styles.background} p-6 shadow-xl transition-all`}

                                >

                                    <div className="flex items-start justify-between">

                                        <div className="flex gap-5">

                                            <div className={`flex h-14 w-14 items-center justify-center rounded-2xl ${styles.icon}`}>

                                                {

                                                    alert.icon === "shield"

                                                        ?

                                                        <ShieldAlert size={28} />

                                                        :

                                                        <ScanSearch size={28} />

                                                }

                                            </div>

                                            <div>

                                                <h2 className={`text-2xl font-bold ${styles.title}`}>

                                                    {alert.title}

                                                </h2>

                                                <div className="mt-4 grid gap-1 text-sm text-zinc-300">

                                                    <p>

                                                        Source IP :
                                                        {" "}
                                                        {alert.source_ip}

                                                    </p>

                                                    <p>

                                                        Attempts :
                                                        {" "}
                                                        {alert.count}

                                                    </p>

                                                    <p>

                                                        Severity :
                                                        {" "}
                                                        {alert.severity}

                                                    </p>

                                                    <p>

                                                        MITRE :
                                                        {" "}
                                                        {alert.mitre}

                                                    </p>

                                                    <p>

                                                        Confidence :
                                                        {" "}
                                                        {alert.confidence}%

                                                    </p>

                                                    <p>

                                                        Detected :
                                                        {" "}
                                                        {alert.detected_at}

                                                    </p>

                                                </div>

                                            </div>

                                        </div>

                                        <div className="flex flex-col items-end gap-4">

                                            <span className={`rounded-full px-4 py-2 text-sm font-bold ${styles.badge}`}>

                                                {alert.severity.toUpperCase()}

                                            </span>

                                            <button

                                                onClick={() => handleInvestigation(alert)}

                                                className="flex items-center gap-2 rounded-xl border border-zinc-700 px-5 py-2 transition hover:border-cyan-500 hover:text-cyan-400"

                                            >

                                                View Investigation

                                                <ChevronRight size={16} />

                                            </button>

                                        </div>

                                    </div>

                                    <div className="mt-5 border-t border-white/10 pt-5 text-zinc-400">

                                        {alert.recommendation}

                                    </div>

                                </motion.div>

                            );

                        })

                    }

                </div>

            </div>

            <AnimatePresence>

                {

                    drawerOpen &&
                    selectedAlert && (

                        <motion.div                             className="fixed inset-0 z-50 flex justify-end bg-black/60 backdrop-blur-sm"

                            initial={{
                                opacity: 0
                            }}

                            animate={{
                                opacity: 1
                            }}

                            exit={{
                                opacity: 0
                            }}

                        >

                            <motion.div

                                initial={{
                                    x: 650
                                }}

                                animate={{
                                    x: 0
                                }}

                                exit={{
                                    x: 650
                                }}

                                transition={{
                                    type: "spring",
                                    stiffness: 260,
                                    damping: 28
                                }}

                                className="flex h-full w-full max-w-2xl flex-col overflow-y-auto border-l border-zinc-800 bg-[#0D1117] shadow-2xl"

                            >

                                <div className="sticky top-0 z-20 flex items-center justify-between border-b border-zinc-800 bg-[#0D1117]/95 px-8 py-6 backdrop-blur">

                                    <div>

    <p className="mb-2 text-xs font-medium uppercase tracking-[0.35em] text-cyan-400">

        Threat Investigation

    </p>

    <h2 className="text-4xl font-black text-white">

        {selectedAlert.title}

    </h2>

    <p
        className={`mt-2 text-lg font-semibold ${
            selectedAlert.severity === "Critical"
                ? "text-red-400"
                : selectedAlert.severity === "High"
                    ? "text-orange-400"
                    : selectedAlert.severity === "Medium"
                        ? "text-yellow-400"
                        : "text-emerald-400"
        }`}
    >

        {selectedAlert.severity}

    </p>

</div>

                                    <button

                                        onClick={closeDrawer}

                                        className="rounded-xl border border-zinc-700 p-2 transition hover:border-red-500 hover:text-red-400"

                                    >

                                        <X size={20} />

                                    </button>

                                </div>

                                <div className="space-y-6 p-8">

                                    <div className="rounded-2xl border border-zinc-800 bg-[#121821] p-6">

                                        <div className="mb-5 flex items-center gap-2">

                                            <Shield
                                                size={18}
                                                className="text-cyan-400"
                                            />

                                            <h3 className="font-semibold">

                                                Incident Summary

                                            </h3>

                                        </div>

                                        <div className="grid grid-cols-2 gap-5">

                                            <SummaryItem
                                                icon={<FileWarning size={16} />}
                                                label="Incident ID"
                                                value={selectedAlert.id}
                                            />

                                            <SummaryItem
                                                icon={<CircleAlert size={16} />}
                                                label="Severity"
                                                value={selectedAlert.severity}
                                            />

                                            <SummaryItem
                                                icon={<MapPin size={16} />}
                                                label="Source IP"
                                                value={selectedAlert.source_ip}
                                            />

                                            <SummaryItem
                                                icon={<Target size={16} />}
                                                label="MITRE ATT&CK"
                                                value={selectedAlert.mitre}
                                            />

                                            <SummaryItem
                                                icon={<Activity size={16} />}
                                                label="Confidence"
                                                value={`${selectedAlert.confidence}%`}
                                            />

                                            <SummaryItem
                                                icon={<Clock3 size={16} />}
                                                label="Detected"
                                                value={selectedAlert.detected_at}
                                            />

                                        </div>

                                    </div>

                                    <div className="rounded-2xl border border-zinc-800 bg-[#121821] p-6">

                                        <div className="mb-5 flex items-center gap-2">

                                            <Target
                                                size={18}
                                                className="text-cyan-400"
                                            />

                                            <h3 className="font-semibold">

                                                Threat Intelligence

                                            </h3>

                                        </div>

                                        <div className="grid grid-cols-3 gap-4">

                                            <ScoreCard
                                                title="Threat"
                                                value={selectedAlert.threat_score}
                                                color="text-red-400"
                                            />

                                            <ScoreCard
                                                title="Risk"
                                                value={selectedAlert.risk_score}
                                                color="text-orange-400"
                                            />

                                            <ScoreCard
                                                title="Confidence"
                                                value={`${selectedAlert.confidence}%`}
                                                color="text-emerald-400"
                                            />

                                        </div>

                                        <div className="mt-8">

                                            <h4 className="mb-4 font-semibold text-cyan-400">

                                                Indicators of Compromise

                                            </h4>

                                            <div className="space-y-5">

                                                {

                                                    Object.entries(selectedAlert.iocs).map(

                                                        ([key, values]) => (

                                                            <div key={key}>

                                                                <p className="mb-2 text-xs uppercase tracking-widest text-zinc-500">

                                                                    {key}

                                                                </p>

                                                                <div className="flex flex-wrap gap-2">

                                                                    {

                                                                        values.length === 0

                                                                            ?

                                                                            <span className="text-zinc-500">

                                                                                —

                                                                            </span>

                                                                            :

                                                                            values.map((value) => (

                                                                                <button

                                                                                    key={value}

                                                                                    className="rounded-lg border border-cyan-500/20 bg-cyan-500/10 px-3 py-1 text-xs text-cyan-300 transition hover:border-cyan-400 hover:bg-cyan-500/20"

                                                                                >

                                                                                    {value}

                                                                                </button>

                                                                            ))

                                                                    }

                                                                </div>

                                                            </div>

                                                        )

                                                    )

                                                }

                                            </div>

                                        </div>

                                    </div>

                                    <div className="rounded-2xl border border-zinc-800 bg-[#121821] p-6">

                                        <h3 className="mb-4 font-semibold">

                                            Recommendation

                                        </h3>

                                        <p className="leading-7 text-zinc-400">

                                            {selectedAlert.recommendation}

                                        </p>

                                    </div>

                                    <div className="grid grid-cols-2 gap-4">

                                        <button

                                            className="flex items-center justify-center gap-2 rounded-xl border border-red-500/30 bg-red-500/10 py-3 font-semibold text-red-400 transition hover:bg-red-500/20"

                                        >

                                            <Ban size={18} />

                                            Block IP

                                        </button>

                                        <button

                                            className="flex items-center justify-center gap-2 rounded-xl border border-cyan-500/30 bg-cyan-500/10 py-3 font-semibold text-cyan-300 transition hover:bg-cyan-500/20"

                                        >

                                            <FileWarning size={18} />

                                            Create Incident

                                        </button>

                                    </div>

                                </div>

                            </motion.div>

                        </motion.div>

                    )

                }

            </AnimatePresence>

        </>

    );

}

function SummaryItem({

    icon,

    label,

    value

}) {

    return (

        <div className="rounded-xl bg-[#0d131b] p-4">

            <div className="mb-2 flex items-center gap-2 text-zinc-500">

                {icon}

                <span className="text-xs uppercase">

                    {label}

                </span>

            </div>

            <p className="font-semibold">

                {value || "--"}

            </p>

        </div>

    );

}

function ScoreCard({

    title,

    value,

    color

}) {

    return (

        <div className="rounded-xl bg-[#0d131b] p-5 text-center">

            <p className="text-xs uppercase tracking-widest text-zinc-500">

                {title}

            </p>

            <p className={`mt-3 text-3xl font-bold ${color}`}>

                {value}

            </p>

        </div>

    );

}